name: hw7_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - pytest
  - numpy 1.21
  - pandas 1.3
  - matplotlib 3.5
  - seaborn 0.11
  - scikit-learn 1.0
  - ipykernel=4.8
  - pyarrow 4.0
  
